<!DOCTYPE html>
<html>
<head>
	<title>Sistema de vendas</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- estilos -->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<!-- script -->
		<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>

<body>
<nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">
        <img src="logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        Prova php
      </a>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="logoff.php">Sair</a>
        </li>
      </ul>
    </nav>

<script>
function myFunction(nome, id) {

const node = document.createElement("li");
node.id = "id_li"
const textnode = document.createTextNode(nome);

node.appendChild(textnode);

document.getElementById("append").appendChild(node);

criarInput(id)
}

var count = 0

function criarInput(id){
	// Create an "li" node:
const node = document.createElement("input");
node.type = "hidden"
node.value = id
node.id = "id_li"
count++
var indice = 0 

while(indice < id){
 indice++ 
}

indice = indice + count

var checkind = document.getElementsByName('id'+indice)
//console.log(checkind.length)
if(checkind.length > 0){
	indice = indice + checkind.length 
}

var checkind = document.getElementsByName('id'+indice)
//console.log(checkind.length)
if(checkind.length > 0){
	indice = indice + checkind.length 
}

node.name = "id"+indice
const textnode = document.createTextNode('oiii');

node.appendChild(textnode);

document.getElementById("append").appendChild(node);
}

function remover(){
	document.getElementById('id_li').outerHTML = ''
	document.getElementById('id_li').outerHTML = ''
}
</script>

    <div class="container mt-5">
      <div class="row">

	  <?php foreach($this->view->produtos as $id_produto => $produto) { ?>

      	<div class="col-md-3">
        <div class="card-consultar-chamado">
          <div class="card">
            <div class="card-header">
              Consulta de chamado
            </div>

            <div class="card-body">

              <div class="card mb-3 bg-light">
                <div class="card-body">
                  <h5 class="card-title" id="titulo"><?= $produto['nome'] ?></h5>
                  <h6 class="card-subtitle mb-2 text-muted"><?= $produto['codigo'] ?></h6>
                  <p class="card-text">R$: <?= $produto['preco'] ?></p>

                </div>
              </div>

              <div class="row mt-5 ">
                <div class="col-6 ">
                  <button class="btn  btn-warning" id="add" 
				  onclick="myFunction('<?php echo ($produto['nome']); ?>', 
				  '<?php echo ($produto['id']); ?>')">Adicionar ao carrinho</button>
                </div>
              </div>
            </div>
          </div>
        </div>
       </div>

	   <?php } ?>

      </div><!--row-->
    </div>

    <section class="mt-5">
    	<div class="container">
			
    		<div class="row">
    			<div>
    				<h4>Carrinho:</h4>
    			</div>

    			<div class="col-md-12">
				<form method="post" action='/venda'>
    				<ul id='append'></ul>
					<button  class="btn btn-danger" type="button" onclick="remover()">Remover Produto</button>
    			</div>
				<button  class="btn btn-primary" type="submit">Finalizar Venda</button>
				<a href="pesquisar_vendas" class="btn btn-primary ml-5" type="button" >Pesquisar Vendas</a>

    		</div>
			
    	</div>
		
    </section>
    <hr>
    <section class="mb-5">
    	<nav class="navbar navbar-light bg-light mb-4">
			<div class="container">
				<div class="navbar-brand mb-0 h1">
					<h3>Pesquisar Endereço</h3>
				</div>
			</div>
		</nav>

		<div class="container">
			<div class="row form-group">
				<div class="col-sm-3">
					<input id="cep" name="cep" type="text" class="form-control" placeholder="CEP"/>
				</div>
				<div class="col-sm-9">
					<input type="text" class="form-control" name="rua" placeholder="Endereço" id='rua' readonly />
				</div>
			</div>

			<div class="row form-group">
				<div class="col-sm-6">
					<input type="text" class="form-control" name="bairro" placeholder="Bairro" id="bairro" readonly />
				</div>
				<div class="col-sm-4">
					<input type="text" class="form-control" name="cidade" placeholder="Cidade" id="cidade" readonly />
				</div>

				<div class="col-sm-2">
					<input type="text" class="form-control" name="uf" placeholder="UF" id='uf' readonly />
				</div>
			</div>
			</form><!--form-->
            <div>
                <button id="botaocep" class="btn btn-warning">Pesquisar endereço</button>
            </div>
		</div>
		<p id="tarefa_1"></p>
    </section>
	<button  class="btn btn-primary" id="vendasss" >Finalizar Venda</button>

<script type="text/javascript">
    	$(document).ready(() => {
			$("#botaocep").click(function(){
                var dados_cep = $('#cep').val()
                var url = 'http://viacep.com.br/ws/' + dados_cep + '/json/'

                var xmlhttp = new XMLHttpRequest()
                xmlhttp.open('GET', url)

                xmlhttp.onreadystatechange = () => {
                    if(xmlhttp.readyState == 4 && xmlhttp.status == 200){
                       var dados_json = xmlhttp.responseText
                       var dados_json_obj = JSON.parse(dados_json)

                       console.log(dados_json_obj)

                     document.getElementById('rua').value = dados_json_obj.logradouro
                     document.getElementById('bairro').value = dados_json_obj.bairro
                     document.getElementById('cidade').value = dados_json_obj.localidade
                     document.getElementById('uf').value = dados_json_obj.uf

                    }
                }

                xmlhttp.send()
});

})
    </script>



</body>
</html>
