<!DOCTYPE html>
<html>
<head>
	<title>Sistema de vendas</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- estilos -->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<!-- script -->
		<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>

<body>
<nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">
        <img src="logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        Prova php
      </a>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="logoff.php">Sair</a>
        </li>
      </ul>
    </nav>

    <section>
      <div class="container my-5">
      <form method="post" action="/pesquisa_bd">
        <div class="row">
           <div class="col-md-11 d-flex justify-content-center">          
                <input class="input input-group" type="text" name="codigo" placeholder="Busque aqui:">
                <button class="btn btn-primary">Buscar</button>    
          </div>
        </div>
        </form>
      </div>
    </section>

 <section>
    <div class="container my-5">
        <div class="row"> 
          <?php //if($_GET['id'] == "1"){ ?>
              <?php foreach($this->view->retorno_vendas12 as $iddd => $retorno) { ?>

                  
                  <?php 
                  $i = 0;
                  $a = 1;
                  foreach($retorno as $idd => $retorno2) {
                  
                  ?>
                    
                  <?php 
                    echo "<pre>";
                        //print_r($retorno2);
                    echo "</pre>";
                    $i = $retorno2['id_venda_nt'];
                    $i = $i - 1;
                    while($i != $retorno2['id_venda_nt']){
                        $i++;
                      //print_r($retorno2['id_venda_nt']);
                      //foreach($retorno2 as $idd => $retorno3) { 
                  ?>
                  <div class="col-md-4 border d-flex justify-content-center">
                  <div class="card-body">
                  <h5 class="card-title" id="titulo">Venda: <?= $retorno2['id_venda_nt'] ?></h5>
                  <h6 class="card-subtitle mb-2 text-muted">Produto: <?=  $retorno2['nome'] ?></h6>
                  <h6 class="card-subtitle mb-2 text-muted">Fornecedor: <?=  $retorno2['nome_fornecedor'] ?></h6>
                  <p class="card-text">Preço venda R$: <?= $retorno2['preco_venda'] ?></p>
                  <p class="card-text">Preço total da venda R$: <?= $retorno2['total_venda'] ?></p>
                  <h5>Endereço de entrega:</h5>
                  <p class="card-text">CEP: <?= $retorno2['CEP'] ?></p>
                  <p class="card-text">UF: <?= $retorno2['UF'] ?></p>
                  <p class="card-text">Cidade: <?= $retorno2['cidade'] ?></p>
                  <p class="card-text">Bairro: <?= $retorno2['bairro'] ?></p>
                  <p class="card-text">Rua: <?= $retorno2['rua'] ?></p>
                  <p class="card-text">Data Venda: <?= $retorno2['data'] ?></p>
                  </div>
                </div>
                  <?php 
                  //while($i != $a){ ?>
                    
                    
                 

                
               
                <?php 
                    //$a++;}
                    }
                    ?>
            <?php 
                    }}
                  //}
                  //} ?>
        </div>
      </div>
  </section>
</body>
</html>
